apiVersion : apps/v1
kind: Deployment
metadata:
  name: react-tic-tac-toe
  labels:
    app: react-tic-tac-toe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-tic-tac-toe
  template:
    metadata:
      labels:
        app: react-tic-tac-toe
    spec:
      containers:
        - name: react-tic-tac-toe
          image: andrewbuttigieg/react-tic-tac-toe:dev
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: react-tic-tac-toe
spec:
    type: NodePort
    ports:
    - port: 80
    selector:
        app: react-tic-tac-toe
